name: vit_large
num_heads: 16
num_blocks: 24
patch_size: 4
embed_dim: 1024
ffn_dim: 4096
dropout: 0.1
max_grad_norm: 1.0
image_size: ${data.image_size}
in_channels: ${data.in_channels}
num_classes: ${data.num_classes}
