defaults:
  - model: vit_base
  - data: cifar100
  - optimizer: adamw
  - _self_

training:
  epochs: 20
  seed: 42
  log_dir: "tensorboard"
  checkpoint_dir: "checkpoints"
  patience: 5
  warmup_epochs: 5
  interactive_save: True

hydra:
  job:
    chdir: True
